### ISSUE TITLE
Compute mutation key failure should return an error

### ISSUE THREAD

**Issue by sullivtr** [sullivtr/terraform-provider-graphql#33]
This line of code simply logs out the error, but does not return an error diagnostic which leads to a false success of the provider's run: https://github.com/sullivtr/terraform-provider-graphql/blob/master/graphql/resource_graphql_mutation.go#L200

**Comment by ajbouh** [comment]
I'm seeing this error and struggling to identify which key is missing. Perhaps the failure message could provide enough info to debug what's going on.

Logging the response at DEBUG level seems like a good thing along these lines.

Also seems like *any* error in the graphql response should be fatal, what do you think?

**Comment by sullivtr** [comment]
Are there other errors you are experiencing that do not return an error correctly? As of now, this is the only error I see that is not actually returning the error correctly, and just eating it up. As for the other errors, they result in a diagnostic being returned to the runner, which is the appropriate way for the provider to error out. That is to say that in cases where errors are fatal, the provider will immediately return an error diag to the runner (This is the current behavior)

**Comment by ajbouh** [comment]
I just confirmed that my create operation itself is actually failing, but the error is being swallowed somewhere. I believe this is contributing the mutation key failure I'm seeing.

**Comment by ajbouh** [comment]
Failures in delete also seem to be swallowed.

**Comment by sullivtr** [comment]
Do you happen to know what status code is being returned on the API request you are using? I have seen some GraphQL APIs unfortunately return 200s for all responses, including errors, which causes the error to be invisible to the provider (The provider's client code is generic, so its not able to imply status on behalf of the API if it does not return a standard err code).

**Comment by ajbouh** [comment]
They all return status 200. I believe the graphql standard specifies that the `"errors"` field on the response object (a sibling to `"data"`) should be authoritative.

So if there's *ever* a non-empty `"errors"` array then perhaps the default behavior should be to fail?

**Comment by sullivtr** [comment]
Thank you for pointing this out. I honestly was not sure about standards in GQL errors when I wrote this provider. That sounds correct. nonetheless. So for this bugfix, I will fix the error response for mutation key lookup failures, as well as enhance the error handling in the query executor. I am not sure when I will get to this, but hopefully sometime this week I will find time.

**Comment by sullivtr** [comment]
@ajbouh I have finally gotten around to handling these errors properly. Soon v2.1.0 will be available which includes fixes that now process graphql server errors appropriately. Please try it out, and also feel free to ask any other questions you may have, or report any issues :)

**Comment by ajbouh** [comment]
Is there a preview version I can try?

**Comment by sullivtr** [comment]
> Is there a preview version I can try?
@ajbouh 
I should be more clear, [v2.1.0](https://github.com/sullivtr/terraform-provider-graphql/releases/tag/v2.1.0) is now available to use.
