### ISSUE TITLE
Feature Request - Destroy and replace instead of update

### ISSUE THREAD

**Issue by robwolff3** [sullivtr/terraform-provider-graphql#37]
Hey sullivtr,

I'm back with another request. In the graphql API I am working with some resources don't that have an update mutation or the update mutation is not very idempotent. Would it be possible to add a true or false input that forces the resource to be destroyed and replaced instead of updated?

Thanks!

P.S. PR-29 has been working great for my implementation and I'm looking forward to PR-35.

**Comment by sullivtr** [comment]
@robwolff3 🤔  I suppose it wouldn't hurt to add a `forceReplace` option. At the moment I can't think of any reason not to support this. Let me add it in my tasks for this project and get something worked out.

**Comment by robwolff3** [comment]
Hey @sullivtr,

Any more thoughts on this feature? I know we ran into the "terraform state processor does not expect a change in computed values and other parts of the state" issue before.

Another idea I had, would this be possible with two versions of the graphql_mutation resource, one that always forces a new resource and another graphql_mutation resource that never forces a new resource?

**Comment by sullivtr** [comment]
Hey @robwolff3, I have dropped the ball in getting this done. I tested a couple of different solutions but each had its own set of adverse bugs that would be very undesirable. I am am still evaluating one other option. (My free time has been restricted the past few months, so apologies for the delay).

**Comment by sullivtr** [comment]
@robwolff3 I believe I have a working solution. Doing some more thorough testing to ensure it works without side effects. Ill keep you posted, and link the PR when it is ready.

**Comment by robwolff3** [comment]
That is exciting 😀 can't wait to test it out. Thank you!

**Comment by sullivtr** [comment]
@robwolff3 [v2.2.0](https://github.com/sullivtr/terraform-provider-graphql/releases/tag/v2.2.0) is now available which includes a boolean field `force_replace`. If set to true, the provider's update lifecycle hook will execute a delete hook, and then recreate the resource using the create mutation.

**Comment by robwolff3** [comment]
🤩 I will test it out as soon as I get back from vacation next week. Thank you!!!
