### ISSUE TITLE
does not work on ARM architectures (apple's M1 for example)

### ISSUE THREAD

**Issue by MDanialSaleem** [sullivtr/terraform-provider-graphql#55]
Hi,

Thanks for the brilliant work on this.

But it gives me this error when I try running on Apple M1 chip:

```
- Finding sullivtr/graphql versions matching "2.2.0"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/sullivtr/graphql v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
```

I don't have a lot of experience building terraform providers I'd be glad to put up a PR for this if you could provide some pointers.

**Comment by sullivtr** [comment]
@MDanialSaleem Thank you for submitting this issue. I believe the only thing we need to do to build for M1 at this point is upgrade the go version to at least 1.16 (currently 1.12, so its overdue for an upgrade). Once we do that, it should begin building for darwin/arm64.

**Comment by sullivtr** [comment]
@MDanialSaleem I plan to get this working in the next release. We are working on a new feature at the moment, so as soon as that is all ready, Ill be cutting a new release that should make the m1 builds work.

**Comment by sullivtr** [comment]
@MDanialSaleem The `v2.4.0` release includes an M1 (darwin/arm64) compatible build. Please try using version 2.4.0 of the provider and let me know if you have any issues.

**Comment by MDanialSaleem** [comment]
@sullivtr , works like a charm, thank you so much for the quick resolution.
