### ISSUE TITLE
Possibly wrong documentation

### ISSUE THREAD

**Issue by samm-git** [sullivtr/terraform-provider-graphql#56]
Readme shows possibly wrong example of the read query:

```md

### Read Query Example
```hcl
mutation getUserByEmail($email: String!) {
  deleteUser(userInput: {
    email: $email
  }) {
    id,
    givenName,
    surname,
    email
  }
}
```

This seems to be copypaste from delete mutation instead.

**Comment by sullivtr** [comment]
@samm-git Indeed there is a typo. `deleteUser` should just be `getUser` for the example. Ill try to sneak this typo fix into the next release.

**Comment by sullivtr** [comment]
This documentation has been updated as part of the v2.4.0 release
