### ISSUE TITLE
Question regarding update mutation

### ISSUE THREAD

**Issue by indrajeet101** [sullivtr/terraform-provider-graphql#73]
Hi,
I am trying to use this provider to perform update operation only. The code is as follows:-

**main.tf** 
```
resource "graphql_mutation" "update_app_settings" {
  mutation_variables = {
    "guid" = "var.guid_of_app"
    "apdexTarget" = "var.apdex_value"
  }

  compute_mutation_keys = {
    "alias" = "agentApplicationSettingsUpdate.alias"
  }

  create_mutation = file("./queries/create_mutation.gql")
  update_mutation = file("./queries/update_mutation.gql")
  delete_mutation = file("./queries/delete_mutation.gql")
  read_query      = file("./queries/query.gql")
}
```
**update_mutation.gql**

```
mutation update($guid:  EntityGuid!, $apdexTarget: Float!) {
    agentApplicationSettingsUpdate(settings: {apmConfig: {apdexTarget: $apdexTarget}}, guid: $guid) {
      apmSettings {
        apmConfig {
          apdexTarget
        }
      }
      alias
    }
}
```
For create and delete I have kept the files blank as for my use case only update mutation is required. Can you please help me in understanding if this will work as I am getting this error  **Error: graphql server error: No query document supplied**.
I believe this occurs because the create mutation file is empty. Is there any workaround that I can use?

**Comment by sullivtr** [comment]
Hello @indrajeet101,

So this is not going to work as you expect. Terraform aims to manage the _full_ CRUD lifecycle of a resource. This provider expects that pattern to be followed. 
If you are unable to manage the full lifecycle of the resource using terraform, than you really should not be using terraform (you _can_, but this will lead to a lot of headaches and confusion in the future for yourself and other developers.)

With that said, what you likely do as a workaround is setup the `create` and `delete` mutations to simply do a read. That is, make them do the same exact thing that your read query does. This _might_ lead to other strange side effects that I cannot predict, but it might just work for your use-case.

**Comment by sullivtr** [comment]
Im going to close this issue since there is not anything I can fix on your behalf other than the provided suggestion. Feel free to comment again if you have further questions
