### ISSUE TITLE
Recurring query_response_input_key_map changes on apply

### ISSUE THREAD

**Issue by jsbnr** [sullivtr/terraform-provider-graphql#75]
Ive tried upgrading to v2.5.2 and setting `enable_remote_state_verification = false` as recommended in issue #70 . It appears to work as intend (thanks, really appreciate the effort here!). However, every time I run an apply with no changes I get the following single update change in the plan appearing:

```
 + query_response_input_key_map        = (known after apply)
```

Im not sure whats causing this to continually appear as a change?

Ive updated my test [example](https://github.com/jsbnr/nr-terraform-graphql-json-dashboards/blob/test-provider-2-5-2/main.tf) with the latest version if thats of any help.

**Comment by sullivtr** [comment]
Hey there. Sorry to hear that. I will look into this today. I thought I sufficiently wrapped that property so it won’t do that, but I must have missed something nuanced. Should be an easy fix tho. 

Appreciate the feedback!

**Comment by sullivtr** [comment]
@jsbnr So after looking at the code, there shouldnt be anything actually changing/modifying the value of that attribute when you have `enable_remote_state_verification = false`.

If possible, can you look at your terraform state and tell me what value its actually setting for that `query_response_input_key_map` attribute? 

There is one small optimization I can make that might also fix this bug, but Im not 💯, so Ill be playing around with that today.

**Comment by jsbnr** [comment]
In the state fiel  it has a value of simply `null` both before and after an apply.

**Comment by sullivtr** [comment]
okay, I think I figured it out. Ill have a PR up soon, and probably get it released this afternoon sometime.

**Comment by sullivtr** [comment]
This fix has been merged. `v2.5.3` should be available within 30 minutes or so (however long it takes for the release automation to run, and for terraform registry to pick it up.

**Comment by jsbnr** [comment]
Works a treat! thanks @sullivtr much appreciated
