### ISSUE TITLE
Apply succeeds without error although 401 Status

### ISSUE THREAD

**Issue by dominik-horb-umg** [sullivtr/terraform-provider-graphql#78]
Due to a misconfiguration on our side we received a 401 Status on our GraphQL API requests when running `terraform apply` with this provider. Even though this happened, a success status of the apply was reported and no errors were shown. We were only able to see the problem, when running with `TF_LOG=DEBUG`. It would be great if any errors of the API calls could be reported by the provider.

**Comment by sullivtr** [comment]
Can you show me what the total response was from your api? This provider checks the standard error params returned for graphql APIs, and so the error parameter should have the error present in the graphql response. If the API you are using is not using that protocol, that is the reason this provider did not pick up the error. I can probably work in some other status code checks but it’s most common for GraphQL APIs to return 200 but only show errors in the error parameter (GraphQL APIs shouldn’t be treated as if they are REST APIs FWIW)

**Comment by dominik-horb-umg** [comment]
Thanks for your response and sorry for the lack of debuggable information in the initial report. I sadly cannot reproduce the exact problem right now and don't have the logs anymore. I saw the problem when interacting with the [Shopify GraphQL API](https://shopify.dev/api/admin-graphql#status_and_error_codes) and I believe it was happening only during the read query of the first apply and on the second apply I then saw an actual error.

Feel free to close if this is not enough information and doesn't ring any obvious bells. I got it working very nicely in the meantime, so thank you for that.

**Comment by sullivtr** [comment]
No problem. I appreciate the report, as it lets me know that there are some nuanced, even sometimes non-idiomatic, use-cases I need to handle for. For the most part, this is working so I will close this issue and whenever I make my next release I will also add some additional status code checks to handle APIs that operate more like traditional http APIs. Thanks again!

**Comment by dominik-horb-umg** [comment]
I think I understand my initial problem now and it had nothing to do with a 401 status. The Shopify GraphQL API uses the `userErrors` field inside the `data` to report on errors, which this module likely cannot easily understand. I tried to alias `userErrors` to `errors`, but I suspect the nesting is also a problem. As an example the create query looks like this:

```gql
mutation EventBridgeWebhookSubscriptionCreate (
  $topic: WebhookSubscriptionTopic!,
  $arn: ARN!,
) {
  eventBridgeWebhookSubscriptionCreate(
    topic: $topic
    webhookSubscription: {
      arn: $arn
      format: JSON
    }
  ) {
    webhookSubscription {
      id
      topic
    }
    errors: userErrors {
      message
      field
    }
  }
}
```

Yielding a result like the following on error:

```json
{
 "data": {
  "eventBridgeWebhookSubscriptionCreate": {
   "webhookSubscription": null,
   "errors": [
    {
     "message": "Address is invalid",
     "field": [
      "webhookSubscription",
      "arn"
     ]
    },
    {
     "message": "Address is not a valid AWS ARN",
     "field": [
      "webhookSubscription",
      "arn"
     ]
    }
   ]
  }
 }
}
```

With this the apply succeeds, even though the desired resource was not created properly.
