### ISSUE TITLE
Set type for computed attributes

### ISSUE THREAD

**Issue by dlecocq** [sullivtr/terraform-provider-graphql#97]
Dealing with a 🤦 API, some endpoints seem to require that for some queries, the `id` be an `Integer`, but for others, a `String`. I know that for providing our own mutation variables, it's possible to make explicit whether we want a string or int (like `"\"123\""`), but it seems there's no way to do that for a _computed_ variable. Any thoughts on how that could be accomplished? I keep getting back an id of `"123"`, but when providing it to the endpoint, it gets recognized as JSON and converted to `123`.

**Comment by sullivtr** [comment]
@dlecocq I merged you MR that was related to this issue, which will be release in v2.5.5.

**Comment by sullivtr** [comment]
https://github.com/sullivtr/terraform-provider-graphql/pull/96
